name: Print Software Versions
on:
  push:
    branches: [ Laboratory-work-4 ]
  workflow_dispatch:

jobs:
  PrintLogicLevelVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version

  PrintDataAccessLevelVersions:
    runs-on: ubuntu-latest
    needs: [PrintLogicLevelVersions]
    steps:
      - name: Print MySQL Version
        run: mysql --version
