name: JavaScript Code Linter
on:
  push:
    branches: [ Laboratory-work-4 ]
  workflow_dispatch:

jobs:
  JavaScriptCodeLinter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install JS Linter Biome
        run: npm install --save-dev --save-exact @biomejs/biome

      - name: Validate all js-files
        run: npx @biomejs/biome check ProgramCodeModified.js
